In [1]:
import pandas as pd

text= """Stock report - exported by finance team
tickers,eps,revenue,price,people
GOOGL,27.82,87,845,larry page
WMT,4.61,484,65,n.a.
MSFT,-1,85,64,bill gates
RIL,not available,50,1023,mukesh ambani
TATA,5.6,-1,n.a.,ratan tata
"""

with open("stock_data.csv",'w') as f:
    f.write(text)

In [ ]:
stock_data=pd.read_csv("stock_data.csv") # that headers are not in better way
print(stock_data)

                                    Stock report - exported by finance team
tickers eps           revenue price                                  people
GOOGL   27.82         87      845                                larry page
WMT     4.61          484     65                                       n.a.
MSFT    -1            85      64                                 bill gates
RIL     not available 50      1023                            mukesh ambani
TATA    5.6           -1      n.a.                               ratan tata

If we have to skiprows : skiprows=no.ofskip

In [18]:
stock_data=pd.read_csv("stock_data.csv",skiprows=2,header=None,names=["Tickets","Eps","Revenue","Price","People"])
print(stock_data)

  Tickets            Eps  Revenue Price         People
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3     RIL  not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [20]:
df=pd.read_csv("stock_data.csv",skiprows=1,na_values={
    'eps':['not available'],
    'revenue':[-1],
    'price':['n.a'],
    'people':['n.a']
})

print(df)

  tickers    eps  revenue price         people
0   GOOGL  27.82     87.0   845     larry page
1     WMT   4.61    484.0    65           n.a.
2    MSFT  -1.00     85.0    64     bill gates
3     RIL    NaN     50.0  1023  mukesh ambani
4    TATA   5.60      NaN  n.a.     ratan tata

In [23]:
df=pd.read_csv("stock_data.csv",skiprows=1,usecols=["tickers","revenue","people"])
print(df)

  tickers  revenue         people
0   GOOGL       87     larry page
1     WMT      484           n.a.
2    MSFT       85     bill gates
3     RIL       50  mukesh ambani
4    TATA       -1     ratan tata

In [26]:
df=pd.read_csv("stock_data.csv",skiprows=1,na_values={
    'eps':['not available'],
    'revenue':[-1],
    'price':['n.a'],
    'people':['n.a']
})

df_excel=df.to_excel("stocks.xlsx",sheet_name="Stock_Data",index=False)

Write the full table and the two-column table into two sheets of one Excel file

In [ ]:
df=pd.read_csv("./files/students.csv",skiprows=2,na_values=["missing"])
orders=pd.read_csv("./files/orders (1).csv",skiprows=1,na_values={
    'price':[-1],
    'rating':['n.a',-1],
    'parse_dates':['order_date']
})

with pd.ExcelWriter("OverallData.xlsx") as writer:
    df.to_excel(writer,sheet_name="Students",index=False)
    orders.to_excel(writer,sheet_name="Orders",index=False)

Missing Data

In [30]:
text = """day,temperature,windspeed,event
1/1/2026,32,6,Rain
1/4/2026,,9,Sunny
1/5/2026,28,,Snow
1/6/2026,,7,
1/7/2026,32,,Rain
1/8/2026,,,Sunny
1/9/2026,,,
1/10/2026,34,8,Cloudy
1/11/2026,40,12,Sunny
"""

with open("weather.csv","w") as f:
    f.write(text)

In [31]:
df=pd.read_csv("weather.csv",parse_dates=["day"])
df

         day  temperature  windspeed   event
0 2026-01-01         32.0        6.0    Rain
1 2026-01-04          NaN        9.0   Sunny
2 2026-01-05         28.0        NaN    Snow
3 2026-01-06          NaN        7.0     NaN
4 2026-01-07         32.0        NaN    Rain
5 2026-01-08          NaN        NaN   Sunny
6 2026-01-09          NaN        NaN     NaN
7 2026-01-10         34.0        8.0  Cloudy
8 2026-01-11         40.0       12.0   Sunny

In [32]:
# Step 1: Measure the Damage
df.isna().sum()

day            0
temperature    4
windspeed      4
event          2
dtype: int64

In [33]:
df.fillna(0).head(4)

         day  temperature  windspeed  event
0 2026-01-01         32.0        6.0   Rain
1 2026-01-04          0.0        9.0  Sunny
2 2026-01-05         28.0        0.0   Snow
3 2026-01-06          0.0        7.0      0

In [34]:
df.fillna({
    'temperature':df['temperature'].mean(),
    'windspeed':0,
    'event':"No Event"
})

         day  temperature  windspeed     event
0 2026-01-01         32.0        6.0      Rain
1 2026-01-04         33.2        9.0     Sunny
2 2026-01-05         28.0        0.0      Snow
3 2026-01-06         33.2        7.0  No Event
4 2026-01-07         32.0        0.0      Rain
5 2026-01-08         33.2        0.0     Sunny
6 2026-01-09         33.2        0.0  No Event
7 2026-01-10         34.0        8.0    Cloudy
8 2026-01-11         40.0       12.0     Sunny

In [39]:
df

         day  temperature  windspeed   event
0 2026-01-01         32.0        6.0    Rain
1 2026-01-04          NaN        9.0   Sunny
2 2026-01-05         28.0        NaN    Snow
3 2026-01-06          NaN        7.0     NaN
4 2026-01-07         32.0        NaN    Rain
5 2026-01-08          NaN        NaN   Sunny
6 2026-01-09          NaN        NaN     NaN
7 2026-01-10         34.0        8.0  Cloudy
8 2026-01-11         40.0       12.0   Sunny

In [ ]:
# forward fill & backward fill
df.ffill()

         day  temperature  windspeed   event
0 2026-01-01         32.0        6.0    Rain
1 2026-01-04         32.0        9.0   Sunny
2 2026-01-05         28.0        9.0    Snow
3 2026-01-06         28.0        7.0    Snow
4 2026-01-07         32.0        7.0    Rain
5 2026-01-08         32.0        7.0   Sunny
6 2026-01-09         32.0        7.0   Sunny
7 2026-01-10         34.0        8.0  Cloudy
8 2026-01-11         40.0       12.0   Sunny

In [41]:
df.bfill(limit=1)

         day  temperature  windspeed   event
0 2026-01-01         32.0        6.0    Rain
1 2026-01-04         28.0        9.0   Sunny
2 2026-01-05         28.0        7.0    Snow
3 2026-01-06         32.0        7.0    Rain
4 2026-01-07         32.0        NaN    Rain
5 2026-01-08          NaN        NaN   Sunny
6 2026-01-09         34.0        8.0  Cloudy
7 2026-01-10         34.0        8.0  Cloudy
8 2026-01-11         40.0       12.0   Sunny

In [45]:
print(df)
nums=df[['temperature','windspeed']]
nums.interpolate().round()

         day  temperature  windspeed   event
0 2026-01-01         32.0        6.0    Rain
1 2026-01-04          NaN        9.0   Sunny
2 2026-01-05         28.0        NaN    Snow
3 2026-01-06          NaN        7.0     NaN
4 2026-01-07         32.0        NaN    Rain
5 2026-01-08          NaN        NaN   Sunny
6 2026-01-09          NaN        NaN     NaN
7 2026-01-10         34.0        8.0  Cloudy
8 2026-01-11         40.0       12.0   Sunny

   temperature  windspeed
0         32.0        6.0
1         30.0        9.0
2         28.0        8.0
3         30.0        7.0
4         32.0        7.0
5         33.0        8.0
6         33.0        8.0
7         34.0        8.0
8         40.0       12.0