In [15]:
import pandas as pd
import numpy as np

df=pd.DataFrame({
    'day':['1/1/2026', '1/2/2026', '1/3/2026', '1/4/2026', '1/5/2026', '1/6/2026'],
    'temperature':[32, -99999, 28, -99999, 32, 31],
    'windspeed':[6, 7, -99999, 7, -88888, 2],
    'event':['Rain', 'Sunny', 'Snow', 'No Event', 'Rain', 'No Event']
})

df

        day  temperature  windspeed     event
0  1/1/2026           32          6      Rain
1  1/2/2026       -99999          7     Sunny
2  1/3/2026           28     -99999      Snow
3  1/4/2026       -99999          7  No Event
4  1/5/2026           32     -88888      Rain
5  1/6/2026           31          2  No Event

In [14]:
# df=df.replace([-99999],np.nan) # Single Value replace
# df=df.replace([-99999,-88888],np.nan) # list of values
df=df.replace({
    'temperature':-99999,
    'windspeed':[-99999,-88888],
    'event':"No Event"
},np.nan)
df

        day  temperature  windspeed  event
0  1/1/2026         32.0        6.0   Rain
1  1/2/2026          NaN        7.0  Sunny
2  1/3/2026         28.0        NaN   Snow
3  1/4/2026          NaN        7.0    NaN
4  1/5/2026         32.0        NaN   Rain
5  1/6/2026         31.0        2.0    NaN

In [11]:
average=df['temperature'].mean()
print(average)

30.75

In [18]:
clean=df.replace({-99999:0,-88888:0,"No Event":"CLear"})
df
clean

        day  temperature  windspeed  event
0  1/1/2026           32          6   Rain
1  1/2/2026            0          7  Sunny
2  1/3/2026           28          0   Snow
3  1/4/2026            0          7  CLear
4  1/5/2026           32          0   Rain
5  1/6/2026           31          2  CLear

In [19]:
messy = pd.DataFrame({'temperature': ['32 F', '28 F', '31 F'],
 'windspeed': ['6 mph', '7 mph', '2 mph'],
 'event': ['Rain', 'Snow', 'Sunny']})

messy

  temperature windspeed  event
0        32 F     6 mph   Rain
1        28 F     7 mph   Snow
2        31 F     2 mph  Sunny

In [22]:
fixed=messy.replace({'temperature':'[A-Za-z]','windspeed':'[A-Za-z]'},'',regex=True)
fixed

  temperature windspeed  event
0         32         6    Rain
1         28         7    Snow
2         31         2   Sunny

In [23]:
reviews = pd.DataFrame({'student': ['Asha', 'Rohit', 'Meera', 'Kabir'],
 'score': ['good', 'poor', 'exceptional', 'average']})

score_num={'poor':1,'good':3,'average':2,'exceptional':4}

reviews["score_num"]=reviews['score'].map(score_num)
reviews

  student        score  score_num
0    Asha         good          3
1   Rohit         poor          1
2   Meera  exceptional          4
3   Kabir      average          2

In [27]:
city = pd.Series(['delhi', 'Delhi ', 'DELHI', 'New Delhi', 'mumbai', 'Bombay'])
# We have to clean the inconsistent data

city=city.str.strip().str.title()
city=city.replace({"New Delhi":"Delhi","Bombay":"Mumbai"})
city
city.value_counts()

Delhi     4
Mumbai    2
Name: count, dtype: int64

1. Create a table where missing ages are written as -1 and missing cities as "NA" or "unknown".
2. Replace all of them with real NaN using one replace call with a dictionary.
3. Add a column of prices written like "Rs 1,200" and convert it to a proper integer column.
4. Map a size column of S / M / L to 1 / 2 / 3.

In [28]:
# 1. Create a table where missing ages are written as -1 and missing cities as "NA" or "unknown".
import pandas as pd
import numpy as np

df=pd.DataFrame({
    'name':["Rahul","Priya","Amit","Sneha","Vikram"],
    'age':[25,-1,32,-1,28],
    'city':["Delhi","Na","Noida","unknown","Mumbai"]
})

df

     name  age     city
0   Rahul   25    Delhi
1   Priya   -1       Na
2    Amit   32    Noida
3   Sneha   -1  unknown
4  Vikram   28   Mumbai

In [29]:
# 2. Replace all of them with real NaN using one replace call with a dictionary.
df=df.replace({'age':{-1:np.nan},"city":{"Na":np.nan,'unknown':np.nan}})
df

     name   age    city
0   Rahul  25.0   Delhi
1   Priya   NaN     NaN
2    Amit  32.0   Noida
3   Sneha   NaN     NaN
4  Vikram  28.0  Mumbai

In [32]:
# 3. Add a column of prices written like "Rs 1,200" and convert it to a proper integer column.
df['price'] = ['Rs 1,200', 'Rs 850', 'Rs 12,500', 'Rs 3,000', 'Rs 450']
df["price"]=df['price'].str.replace("Rs","",regex=False).str.replace(",",'',regex=False).str.strip().astype(int)

df["price"]

0     1200
1      850
2    12500
3     3000
4      450
Name: price, dtype: int64

In [34]:
# 4. Map a size column of S / M / L to 1 / 2 / 3.
df['size']=['M','L','S','S','M']
df['size_code']=df['size'].map({'S':1,"M":2,"L":3})
df

     name   age    city  price size  size_code
0   Rahul  25.0   Delhi   1200    M          2
1   Priya   NaN     NaN    850    L          3
2    Amit  32.0   Noida  12500    S          1
3   Sneha   NaN     NaN   3000    S          1
4  Vikram  28.0  Mumbai    450    M          2